// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYMFuaC7ThuWcePMWYYPVLn8j0EONtP-k',
    appId: '1:320826225712:web:d57b98d5c87c8bf1baa9f5',
    messagingSenderId: '320826225712',
    projectId: 'mobile-absensi-6d1a7',
    authDomain: 'mobile-absensi-6d1a7.firebaseapp.com',
    databaseURL: 'https://mobile-absensi-6d1a7-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-absensi-6d1a7.appspot.com',
    measurementId: 'G-2RMJPX49CR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkH3F-aznk2XRlXQgbzQDHmru87Vk-NZU',
    appId: '1:320826225712:android:15f2f6bb47eddf39baa9f5',
    messagingSenderId: '320826225712',
    projectId: 'mobile-absensi-6d1a7',
    databaseURL: 'https://mobile-absensi-6d1a7-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-absensi-6d1a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEnecj0UfDwisMRS6AObTas7nNECKAQ3I',
    appId: '1:320826225712:ios:b74fc246af57bfb0baa9f5',
    messagingSenderId: '320826225712',
    projectId: 'mobile-absensi-6d1a7',
    databaseURL: 'https://mobile-absensi-6d1a7-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-absensi-6d1a7.appspot.com',
    iosBundleId: 'com.pasbar.mobileabsensi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEnecj0UfDwisMRS6AObTas7nNECKAQ3I',
    appId: '1:320826225712:ios:7de89317e1ee51e9baa9f5',
    messagingSenderId: '320826225712',
    projectId: 'mobile-absensi-6d1a7',
    databaseURL: 'https://mobile-absensi-6d1a7-default-rtdb.firebaseio.com',
    storageBucket: 'mobile-absensi-6d1a7.appspot.com',
    iosBundleId: 'com.pasbar.mobileabsensi.RunnerTests',
  );
}
